create table veiculo (
	id integer generated by default as identity,
	nome varchar(255) not null,
	marca varchar(255) not null,
	modelo varchar(255) not null,
	ano_fabricacao integer not null,
	consumo_cidade double not null,
	consumo_rodovia double not null,
	primary key (id)
);